CircleCI Config Changes
phovea/generator-phovea pull request #436
Opened 2020-11-03 08:48 UTC by anita-steiner

see #433 

there will be a follow-up issue to redesign the build.js and the init_product circleci config

2020-11-13 08:58 UTC, thinkh requested changes
Only some minor remarks / changes necessary. The rest looks fine. I haven't tested it with an existing repo or product.

2020-11-13 08:58 UTC, thinkh commented on generators/_init-hybrid/templates/plain/.circleci/config.yml
> +      - image: circleci/node:12.13-buster-browsers # for node version see Dockerfile on https://hub.docker.com/r/circleci/python
```suggestion
      - image: circleci/node:12.13-buster-browsers
```

2020-11-13 08:58 UTC, thinkh commented on generators/_init-web/templates/plain/.circleci/config.yml
> +      - image: circleci/node:12.13-buster-browsers # for node version see Dockerfile on https://hub.docker.com/r/circleci/python
```suggestion
      - image: circleci/node:12.13-buster-browsers
```

2020-11-13 08:58 UTC, thinkh commented on generators/_init-hybrid/templates/plain/.circleci/config.yml
> +                ignore: /.*/
Fix code indentation

2020-11-13 08:58 UTC, thinkh commented on generators/_init-hybrid/templates/plain/.circleci/config.yml
>  #      - build
Also update the build steps here. So that the workflow still works when uncommenting.

2020-11-13 09:33 UTC, thinkh approved these changes
Looks good to me now.

2021-02-15 09:27 UTC, dvvanessastoiber approved these changes
Looks good to me, thank you :+1:

2021-02-15 09:27 UTC, merged